import type { Endpoint, GeneratedFile } from "./types";
import { toPascal, toCamel } from "./types";

function methodHasBody(method: string) {
  return method === "POST" || method === "PUT" || method === "PATCH";
}

function tsParamType(path: string): string {
  const params = [...path.matchAll(/:([a-zA-Z_]+)/g)].map((m) => m[1]);
  if (params.length === 0) return "";
  return `{ ${params.map((p) => `${p}: string`).join("; ")} }`;
}

function tsPathInterpolation(path: string): string {
  return "`" + path.replace(/:([a-zA-Z_]+)/g, "${params.$1}") + "`";
}

function tsEndpointFn(e: Endpoint): string {
  const name = toCamel(
    e.summary.replace(/[^a-zA-Z0-9]+/g, " ").trim().replace(/\s+(.)/g, (_, c: string) => c.toUpperCase()) || `${e.method.toLowerCase()}${toPascal(e.path.replace(/[:\/]/g, "_"))}`
  );
  const paramType = tsParamType(e.path);
  const hasBody = methodHasBody(e.method);
  const hasParams = paramType !== "";

  const args: string[] = [];
  if (hasParams) args.push(`params: ${paramType}`);
  if (hasBody) args.push(`body: Record<string, unknown>`);
  args.push(`options?: RequestInit`);

  const pathExpr = hasParams ? tsPathInterpolation(e.path) : `"${e.path}"`;

  const authHeader = e.auth
    ? `\n    ...(token ? { Authorization: \`Bearer \${token}\` } : {}),`
    : "";

  const bodyPart = hasBody
    ? `\n    body: JSON.stringify(body),`
    : "";

  return `  async ${name}(${args.join(", ")}) {
    return this.request(${pathExpr}, {
      method: "${e.method}",
      headers: { "Content-Type": "application/json",${authHeader} },${bodyPart}
      ...options,
    });
  }`;
}

export function clientSdkTs(baseUrl: string, endpoints: Endpoint[]): string {
  const fns = endpoints.map(tsEndpointFn).join(",\n\n");
  return `// Auto-generated by Helios — do not edit manually.
// Regenerate by re-downloading the stack from https://helios.app

const BASE_URL = process.env.API_URL ?? "${baseUrl}";

export class HeliosClient {
  private baseUrl: string;
  private token: string | null;

  constructor(baseUrl = BASE_URL, token: string | null = null) {
    this.baseUrl = baseUrl;
    this.token = token;
  }

  withToken(token: string): this {
    this.token = token;
    return this;
  }

  private async request(path: string, init: RequestInit = {}): Promise<Response> {
    const res = await fetch(this.baseUrl + path, init);
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(\`\${init.method ?? "GET"} \${path} failed (\${res.status}): \${text}\`);
    }
    return res;
  }

${fns}
}

export const client = new HeliosClient();
`;
}

function pyParamList(path: string): string[] {
  return [...path.matchAll(/:([a-zA-Z_]+)/g)].map((m) => m[1]);
}

function pyPathInterpolation(path: string): string {
  return `f"${path.replace(/:([a-zA-Z_]+)/g, "{$1}")}"`;
}

function pyEndpointFn(e: Endpoint): string {
  const name =
    e.summary
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") ||
    `${e.method.toLowerCase()}_${e.path.replace(/[:\/]/g, "_").replace(/^_+|_+$/g, "")}`;

  const pathParams = pyParamList(e.path);
  const hasBody = methodHasBody(e.method);

  const args = ["self", ...pathParams.map((p) => `${p}: str`)];
  if (hasBody) args.push(`body: dict | None = None`);
  args.push(`**kwargs: Any`);

  const pathExpr = pathParams.length > 0 ? pyPathInterpolation(e.path) : `"${e.path}"`;

  const bodyLine = hasBody
    ? `\n        kwargs.setdefault("json", body or {})`
    : "";

  const headers = e.auth
    ? `\n        if self._token:\n            kwargs.setdefault("headers", {})["Authorization"] = f"Bearer {self._token}"`
    : "";

  return `    def ${name}(self, ${args.join(", ")}) -> httpx.Response:
        """${e.method} ${e.path}${e.summary ? ` — ${e.summary}` : ""}"""${headers}${bodyLine}
        return self._request("${e.method}", ${pathExpr}, **kwargs)`;
}

export function clientSdkPy(baseUrl: string, endpoints: Endpoint[]): string {
  const fns = endpoints.map(pyEndpointFn).join("\n\n");
  return `# Auto-generated by Helios — do not edit manually.
# Regenerate by re-downloading the stack from https://helios.app
from __future__ import annotations

import os
from typing import Any

import httpx

_BASE_URL = os.getenv("API_URL", "${baseUrl}")


class HeliosClient:
    def __init__(self, base_url: str = _BASE_URL, token: str | None = None) -> None:
        self._base_url = base_url.rstrip("/")
        self._token = token
        self._http = httpx.Client(base_url=self._base_url)

    def with_token(self, token: str) -> "HeliosClient":
        self._token = token
        return self

    def _request(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        res = self._http.request(method, path, **kwargs)
        res.raise_for_status()
        return res

${fns}

    def __enter__(self) -> "HeliosClient":
        return self

    def __exit__(self, *_: object) -> None:
        self._http.close()


client = HeliosClient()
`;
}

export function clientSdkFiles(name: string, endpoints: Endpoint[]): GeneratedFile[] {
  if (endpoints.length === 0) return [];
  const baseUrl = `http://localhost:8080`;
  return [
    {
      path: `sdk/${name}-client.ts`,
      content: clientSdkTs(baseUrl, endpoints),
    },
    {
      path: `sdk/${name}_client.py`,
      content: clientSdkPy(baseUrl, endpoints),
    },
  ];
}
