import type { Endpoint, GeneratedFile, StackConfig } from "./types";
import { safeName, toEnvKey } from "./types";

const languageMeta: Record<
  StackConfig["language"],
  { runCommand: string; testCommand: string; devCommand: string }
> = {
  go: { runCommand: "go run ./cmd/api", testCommand: "go test ./... -race -cover", devCommand: "go run ./cmd/api" },
  typescript: { runCommand: "npm run start", testCommand: "npm test", devCommand: "npm run dev" },
  python: { runCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8080", testCommand: "pytest -q", devCommand: "uvicorn app.main:app --reload" },
  rust: { runCommand: "cargo run --release", testCommand: "cargo test", devCommand: "cargo run" },
  java: { runCommand: "./mvnw spring-boot:run", testCommand: "./mvnw test", devCommand: "./mvnw spring-boot:run" },
  kotlin: { runCommand: "./gradlew run", testCommand: "./gradlew test", devCommand: "./gradlew run" },
};

const langEmoji: Record<StackConfig["language"], string> = {
  go: "Go",
  typescript: "TypeScript",
  python: "Python",
  rust: "Rust",
  java: "Java",
  kotlin: "Kotlin",
};

export function commonFiles(
  config: StackConfig,
  endpoints: Endpoint[]
): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const meta = languageMeta[config.language];
  const name = safeName(config.name);

  files.push({
    path: "README.md",
    content: readme(config, endpoints, meta),
  });

  files.push({ path: ".env.example", content: envExample(config) });
  files.push({ path: ".gitignore", content: gitignore(config.language) });
  files.push({
    path: ".editorconfig",
    content:
      "root = true\n\n[*]\nend_of_line = lf\ncharset = utf-8\nindent_style = space\nindent_size = 2\ntrim_trailing_whitespace = true\ninsert_final_newline = true\n",
  });

  if (config.docker) {
    files.push({ path: "docker-compose.yml", content: dockerCompose(config) });
  }

  if (config.kubernetes) {
    files.push({
      path: "deploy/k8s/deployment.yaml",
      content: k8sDeployment(config),
    });
    files.push({
      path: "deploy/k8s/service.yaml",
      content: k8sService(config),
    });
    if (config.autoscale) {
      files.push({
        path: "deploy/k8s/hpa.yaml",
        content: k8sHPA(config),
      });
    }
  }

  if (config.helm) {
    files.push({
      path: "deploy/helm/Chart.yaml",
      content: helmChart(name),
    });
    files.push({
      path: "deploy/helm/values.yaml",
      content: helmValues(config),
    });
    files.push({
      path: "deploy/helm/templates/deployment.yaml",
      content: helmDeploymentTemplate(),
    });
    files.push({
      path: "deploy/helm/templates/service.yaml",
      content: helmServiceTemplate(),
    });
  }

  files.push({
    path: ".github/workflows/ci.yml",
    content: ciWorkflow(config),
  });

  files.push({
    path: "api/openapi.yaml",
    content: openapiSpec(config, endpoints),
  });

  return files;
}

function readme(
  config: StackConfig,
  endpoints: Endpoint[],
  meta: (typeof languageMeta)[StackConfig["language"]]
) {
  const ep = endpoints
    .map((e) => `| \`${e.method}\` | \`${e.path}\` | ${e.summary}${e.auth ? " | 🔐" : " | —"} |`)
    .join("\n");
  return `# ${config.name}

Generated by **Helios** — an AI-native backend generator.

> ${langEmoji[config.language]} · ${config.framework} · ${config.database} · ${config.cache} · ${config.api.toUpperCase()} · ${config.deployment}

## Quickstart

\`\`\`bash
cp .env.example .env
${config.docker ? "docker compose up --build" : meta.devCommand}
\`\`\`

## Scripts

| Command | Purpose |
| --- | --- |
| \`${meta.devCommand}\` | Run locally with hot reload |
| \`${meta.runCommand}\` | Start the API server |
| \`${meta.testCommand}\` | Run the test suite |

## Endpoints

| Method | Path | Summary | Auth |
| --- | --- | --- | --- |
${ep || "| — | — | _no endpoints defined_ | — |"}

## Deploy

Target: **${config.deployment}** · Region: \`${config.region}\` · Baseline replicas: ${config.replicas}${config.autoscale ? " (autoscaling enabled)" : ""}.

- Dockerfile and docker-compose at the repo root
- Kubernetes manifests under \`deploy/k8s/\`${config.helm ? "\n- Helm chart under `deploy/helm/`" : ""}
- CI wired for ${config.cicd} at \`.github/workflows/ci.yml\`

## Observability

${config.monitoring} is wired in with sensible defaults.${config.tracing ? " OpenTelemetry traces are exported via OTLP." : ""}${config.audit ? " Audit logs are emitted for every mutating request." : ""}
`;
}

function envExample(config: StackConfig) {
  const lines = [
    `# Runtime`,
    `APP_NAME=${config.name}`,
    `LOG_LEVEL=info`,
    `PORT=8080`,
    ``,
  ];
  for (const v of config.envVars) {
    lines.push(`${toEnvKey(v.key)}=${v.secret ? "change-me" : v.value}`);
  }
  return lines.join("\n") + "\n";
}

function gitignore(language: StackConfig["language"]) {
  const base = `# env
.env
.env.*
!.env.example

# editor
.idea/
.vscode/
.DS_Store

# build
dist/
out/
build/
coverage/

# logs
*.log
npm-debug.log*
`;
  const langMap: Record<StackConfig["language"], string> = {
    go: "\n# go\n/bin/\n*.test\n*.out\nvendor/\n",
    typescript: "\n# node\nnode_modules/\n.next/\n.nuxt/\n.turbo/\n.tsbuildinfo\n",
    python: "\n# python\n__pycache__/\n*.pyc\n.venv/\nvenv/\n.pytest_cache/\n.mypy_cache/\n.ruff_cache/\n",
    rust: "\n# rust\n/target/\n",
    java: "\n# java\n/target/\n.gradle/\nbuild/\n",
    kotlin: "\n# kotlin\n/target/\n.gradle/\nbuild/\n",
  };
  return base + langMap[language];
}

function dockerCompose(config: StackConfig) {
  const services: string[] = [
    `  api:
    build: .
    ports:
      - "8080:8080"
    env_file: [.env]
    depends_on:${config.database ? "\n      - db" : ""}${config.cache ? "\n      - cache" : ""}${config.queue === "rabbitmq" ? "\n      - rabbit" : ""}${config.queue === "kafka" ? "\n      - kafka" : ""}`,
  ];

  if (/postgres|supabase|neon/.test(config.database)) {
    services.push(`  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: \${POSTGRES_DB:-${safeName(config.name)}}
    ports: ["5432:5432"]
    volumes: [db-data:/var/lib/postgresql/data]`);
  } else if (config.database === "mysql" || config.database === "planetscale") {
    services.push(`  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: ${safeName(config.name)}
    ports: ["3306:3306"]
    volumes: [db-data:/var/lib/mysql]`);
  } else if (config.database === "mongodb") {
    services.push(`  db:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [db-data:/data/db]`);
  } else if (config.database === "cockroach") {
    services.push(`  db:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports: ["26257:26257", "8081:8080"]
    volumes: [db-data:/cockroach/cockroach-data]`);
  }

  if (config.cache === "redis" || config.cache === "upstash") {
    services.push(`  cache:
    image: redis:7-alpine
    ports: ["6379:6379"]`);
  } else if (config.cache === "memcached") {
    services.push(`  cache:
    image: memcached:1.6-alpine
    ports: ["11211:11211"]`);
  } else if (config.cache === "dragonfly") {
    services.push(`  cache:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports: ["6379:6379"]`);
  }

  if (config.queue === "rabbitmq") {
    services.push(`  rabbit:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]`);
  } else if (config.queue === "kafka") {
    services.push(`  kafka:
    image: redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false
    ports: ["9092:9092"]`);
  } else if (config.queue === "nats") {
    services.push(`  nats:
    image: nats:2-alpine
    command: ["-js"]
    ports: ["4222:4222"]`);
  }

  return `services:
${services.join("\n\n")}

volumes:
  db-data: {}
`;
}

function k8sDeployment(config: StackConfig) {
  const name = safeName(config.name);
  return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  labels:
    app: ${name}
spec:
  replicas: ${config.replicas}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/${name}:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ${name}-env
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 2
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
          resources:
            requests: { cpu: 250m, memory: 256Mi }
            limits:   { cpu: 1,    memory: 512Mi }
`;
}

function k8sService(config: StackConfig) {
  const name = safeName(config.name);
  return `apiVersion: v1
kind: Service
metadata:
  name: ${name}
spec:
  selector:
    app: ${name}
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
`;
}

function k8sHPA(config: StackConfig) {
  const name = safeName(config.name);
  return `apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  minReplicas: ${config.replicas}
  maxReplicas: ${Math.max(config.replicas * 4, 10)}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
`;
}

function helmChart(name: string) {
  return `apiVersion: v2
name: ${name}
description: Generated by Helios
type: application
version: 0.1.0
appVersion: "0.1.0"
`;
}

function helmValues(config: StackConfig) {
  const name = safeName(config.name);
  return `replicaCount: ${config.replicas}

image:
  repository: ghcr.io/your-org/${name}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: ${config.autoscale}
  minReplicas: ${config.replicas}
  maxReplicas: ${Math.max(config.replicas * 4, 10)}
  targetCPUUtilizationPercentage: 65

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi
`;
}

function helmDeploymentTemplate() {
  return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
`;
}

function helmServiceTemplate() {
  return `apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
`;
}

function ciWorkflow(config: StackConfig) {
  const lang = config.language;
  const common = `name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
`;
  const lint = `      - name: Lint
        run: echo "run your linter here"
`;
  if (lang === "go") {
    return (
      common +
      `      - uses: actions/setup-go@v5
        with: { go-version: '1.23' }
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./... -race -cover
      - name: Build
        run: go build ./...
`
    );
  }
  if (lang === "typescript") {
    return (
      common +
      `      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm test --if-present
      - run: npm run build --if-present
`
    );
  }
  if (lang === "python") {
    return (
      common +
      `      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install -e .[dev]
      - run: pytest -q || true
`
    );
  }
  if (lang === "rust") {
    return (
      common +
      `      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all
      - run: cargo build --release
`
    );
  }
  if (lang === "java") {
    return (
      common +
      `      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21' }
      - run: ./mvnw -B test
`
    );
  }
  // kotlin
  return (
    common +
    `      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21' }
      - run: ./gradlew test
`
  );
}

function openapiSpec(config: StackConfig, endpoints: Endpoint[]) {
  const byPath = new Map<string, Endpoint[]>();
  for (const e of endpoints) {
    const key = e.path.replace(/:([a-zA-Z0-9_]+)/g, "{$1}");
    byPath.set(key, [...(byPath.get(key) ?? []), e]);
  }
  const paths: string[] = [];
  for (const [p, eps] of byPath) {
    paths.push(`  ${p}:`);
    for (const e of eps) {
      paths.push(`    ${e.method.toLowerCase()}:`);
      paths.push(`      summary: ${JSON.stringify(e.summary)}`);
      paths.push(`      operationId: ${operationId(e)}`);
      if (e.auth) paths.push(`      security: [{ bearerAuth: [] }]`);
      paths.push(`      responses:`);
      paths.push(`        "200":`);
      paths.push(`          description: OK`);
      if (e.responseSchema) {
        paths.push(`          content:`);
        paths.push(`            application/json:`);
        paths.push(`              schema:`);
        paths.push(
          `                $ref: "#/components/schemas/${e.responseSchema}"`
        );
      }
    }
  }

  return `openapi: 3.1.0
info:
  title: ${config.name}
  version: 0.1.0
  description: Generated by Helios.
servers:
  - url: https://api.example.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
${paths.join("\n") || "  /health:\n    get:\n      summary: Liveness\n      responses:\n        '200': { description: ok }"}
`;
}

export function operationId(e: Endpoint) {
  return (
    e.method.toLowerCase() +
    e.path
      .split("/")
      .filter(Boolean)
      .map((p) => {
        if (p.startsWith(":")) return "By" + p.slice(1, 2).toUpperCase() + p.slice(2);
        return p[0].toUpperCase() + p.slice(1);
      })
      .join("")
  );
}
