import type { Endpoint, Entity, FieldType, GeneratedFile, StackConfig } from "./types";

export function pythonFiles(
  config: StackConfig,
  endpoints: Endpoint[],
  entities: Entity[] = []
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  files.push({ path: "pyproject.toml", content: pyproject(config, entities.length > 0) });
  files.push({ path: "Dockerfile", content: pyDockerfile() });
  files.push({ path: "app/__init__.py", content: "" });
  files.push({
    path: "app/main.py",
    content: appMain(config, endpoints),
  });
  files.push({
    path: "app/config.py",
    content: `from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    app_name: str = "app"
    log_level: str = "info"
    database_url: str | None = None
    redis_url: str | None = None
    jwt_secret: str | None = None

    class Config:
        env_file = ".env"

settings = Settings()
`,
  });

  if (entities.length > 0) {
    files.push({ path: "app/models.py", content: sqlalchemyModels(config, entities) });
  }

  return files;
}

function sqlalchemyModels(config: StackConfig, entities: Entity[]): string {
  const isMongo = /mongo/.test(config.database);

  if (isMongo) {
    const docs = entities
      .map((e) => {
        const fields = e.fields
          .filter((f) => !f.primaryKey)
          .map((f) => `    ${f.name}: ${pyType(f.type)}${f.required ? "" : " | None"} = None`);
        return `class ${e.name}(BaseModel):\n    id: str = Field(default_factory=lambda: str(uuid.uuid4()))\n${fields.join("\n")}`;
      })
      .join("\n\n");

    return `# Auto-generated by Helios — edit freely
from pydantic import BaseModel, Field
import uuid

${docs}
`;
  }

  const isPostgres = /postgres|neon|supabase|cockroach/.test(config.database);

  const models = entities
    .map((e) => {
      const tableName = e.name.toLowerCase() + "s";
      const cols = e.fields.map((f) => {
        const colType = saColType(f.type, isPostgres);
        const pk = f.primaryKey ? ", primary_key=True" : "";
        const uniq = f.unique && !f.primaryKey ? ", unique=True" : "";
        const nullable = !f.required && !f.primaryKey ? ", nullable=True" : "";
        const default_ = f.primaryKey && f.type === "uuid" ? ", default=uuid.uuid4" : "";
        return `    ${f.name} = Column(${colType}${pk}${default_}${uniq}${nullable})`;
      });
      if (!e.fields.some((f) => f.name === "createdAt"))
        cols.push("    created_at = Column(DateTime, default=datetime.utcnow)");
      if (!e.fields.some((f) => f.name === "updatedAt"))
        cols.push("    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)");

      return `class ${e.name}(Base):\n    __tablename__ = "${tableName}"\n${cols.join("\n")}`;
    })
    .join("\n\n");

  return `# Auto-generated by Helios — edit freely
from sqlalchemy import Column, String, Integer, Boolean, DateTime, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import DeclarativeBase
from datetime import datetime
import uuid


class Base(DeclarativeBase):
    pass


${models}
`;
}

function pyType(t: FieldType): string {
  switch (t) {
    case "uuid":    return "str";
    case "string":  return "str";
    case "text":    return "str";
    case "number":  return "int";
    case "boolean": return "bool";
    case "date":    return "str";
    case "json":    return "dict";
  }
}

function saColType(t: FieldType, isPostgres: boolean): string {
  switch (t) {
    case "uuid":    return isPostgres ? "UUID(as_uuid=True)" : "String(36)";
    case "string":  return "String(255)";
    case "text":    return "Text";
    case "number":  return "Integer";
    case "boolean": return "Boolean";
    case "date":    return "DateTime";
    case "json":    return isPostgres ? "JSONB" : "Text";
  }
}

function pyproject(config: StackConfig, withModels = false) {
  const isPostgres = /postgres|neon|supabase|cockroach/.test(config.database);
  const sqlDeps = withModels && !(/mongo/.test(config.database))
    ? `\nsqlalchemy = "^2.0.0"\n${isPostgres ? `psycopg2-binary = "^2.9.0"\n` : ""}`
    : "";
  const deps =
    config.framework === "fastapi"
      ? `fastapi = "^0.115.0"\nuvicorn = { extras = ["standard"], version = "^0.30.0" }\npydantic = "^2.9.0"\npydantic-settings = "^2.5.0"${sqlDeps}`
      : config.framework === "litestar"
      ? `litestar = { extras = ["standard"], version = "^2.12.0" }\npydantic-settings = "^2.5.0"${sqlDeps}`
      : `django = "^5.1.0"\npydantic-settings = "^2.5.0"${sqlDeps}`;
  return `[project]
name = "${config.name}"
version = "0.1.0"
requires-python = ">=3.12"

[tool.poetry.dependencies]
python = "^3.12"
${deps}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
httpx = "^0.27.0"
`;
}

function pyDockerfile() {
  return `# syntax=docker/dockerfile:1
FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY pyproject.toml ./
RUN pip install --no-cache-dir poetry==1.8.3 && poetry config virtualenvs.create false && poetry install --only main --no-root || pip install fastapi uvicorn pydantic pydantic-settings
COPY . .
EXPOSE 8080
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
`;
}

function appMain(config: StackConfig, endpoints: Endpoint[]) {
  if (config.framework === "fastapi") {
    const routes = endpoints
      .map((e) => {
        const py = e.path.replace(/:([a-zA-Z0-9_]+)/g, "{$1}");
        const paramsDecl = (e.path.match(/:([a-zA-Z0-9_]+)/g) ?? [])
          .map((p) => `${p.slice(1)}: str`)
          .join(", ");
        return `@app.${e.method.toLowerCase()}(${JSON.stringify(py)})
async def ${handlerName(e)}(${paramsDecl}):
    return {"ok": True, "op": "${e.method} ${e.path}"}`;
      })
      .join("\n\n");
    return `from fastapi import FastAPI, Depends, HTTPException, Header
from .config import settings

app = FastAPI(title=settings.app_name)

async def auth_required(authorization: str | None = Header(default=None)):
    if not authorization:
        raise HTTPException(status_code=401, detail="unauthorized")

@app.get("/health")
async def health():
    return {"ok": True}

${routes}
`;
  }
  if (config.framework === "litestar") {
    return `from litestar import Litestar, get

@get("/health")
async def health() -> dict:
    return {"ok": True}

app = Litestar(route_handlers=[health])
`;
  }
  // django minimal
  return `# Minimal Django entrypoint — see deploy/k8s for production setup
from django.http import JsonResponse
from django.urls import path

def health(_):
    return JsonResponse({"ok": True})

urlpatterns = [path("health", health)]
`;
}

function handlerName(e: Endpoint) {
  const parts = e.path
    .split("/")
    .filter(Boolean)
    .map((p) => (p.startsWith(":") ? "by_" + p.slice(1) : p.replace(/[^a-zA-Z0-9]/g, "_")));
  return (e.method.toLowerCase() + "_" + parts.join("_")).replace(/_+$/g, "");
}
