"use client";

import * as React from "react";
import {
  AlertCircle,
  Check,
  ChevronDown,
  ExternalLink,
  GitBranch,
  Github,
  Loader2,
  RefreshCw,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useStackStore } from "@/lib/store";
import { toast } from "@/components/ui/toast";
import { cn } from "@/lib/utils";

type GhStatus = { connected: boolean; login?: string; avatarUrl?: string } | null;
type Branch = { name: string; protected: boolean };
type PRResult = { prUrl: string; prNumber: number; branchName: string; fileCount: number };

function slugDate() {
  const d = new Date();
  return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}`;
}

function defaultBranchName(prefix: string, projectName: string) {
  return `${prefix}/${projectName}-${slugDate()}`.replace(/[^a-zA-Z0-9/_-]/g, "-");
}

function defaultPrBody(config: { language: string; framework: string; database: string }, fileCount: number) {
  return `## Summary

Generated backend infrastructure by **Helios**.

- **Language:** ${config.language}
- **Framework:** ${config.framework}
- **Database:** ${config.database}
- **Files:** ${fileCount} generated files

## What's included

- Application entry point + routing
- Database models and migrations
- Docker + docker-compose
- CI/CD workflow (GitHub Actions)
- OpenAPI spec
- Environment variable templates

## Test plan

- [ ] \`docker compose up\` runs cleanly
- [ ] \`/health\` endpoint returns 200
- [ ] CI checks pass

---
*Generated by [Helios](https://helios.sh)*`;
}

export function PRCreator() {
  const { config, endpoints, entities, gitConfig } = useStackStore();

  const [ghStatus, setGhStatus] = React.useState<GhStatus>(null);
  const [loadingStatus, setLoadingStatus] = React.useState(true);

  const [repoInput, setRepoInput] = React.useState("");
  const [repoError, setRepoError] = React.useState<string | null>(null);

  const [branches, setBranches] = React.useState<Branch[]>([]);
  const [loadingBranches, setLoadingBranches] = React.useState(false);
  const [branchesLoaded, setBranchesLoaded] = React.useState(false);

  const [baseBranch, setBaseBranch] = React.useState("main");
  const [branchName, setBranchName] = React.useState("");
  const [prTitle, setPrTitle] = React.useState("");
  const [prBody, setPrBody] = React.useState("");

  const [submitting, setSubmitting] = React.useState(false);
  const [result, setResult] = React.useState<PRResult | null>(null);
  const [submitError, setSubmitError] = React.useState<string | null>(null);

  // Load GitHub connection status
  React.useEffect(() => {
    setLoadingStatus(true);
    fetch("/api/auth/github/status")
      .then((r) => r.json())
      .then((d: { connected: boolean; login?: string; avatarUrl?: string }) => setGhStatus(d))
      .catch(() => setGhStatus({ connected: false }))
      .finally(() => setLoadingStatus(false));
  }, []);

  // Pre-fill branch name and PR title when config loads
  React.useEffect(() => {
    const prefix = gitConfig.branchNaming.feature.split("/")[0] ?? "feat";
    setBranchName(defaultBranchName(prefix, config.name));
    setPrTitle(`feat: generated ${config.name} (${config.language}/${config.framework})`);
    setPrBody(defaultPrBody(config, 0));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config.name, config.language, config.framework, config.database, gitConfig.branchNaming.feature]);

  function parseRepo(input: string): { owner: string; repo: string } | null {
    const clean = input.trim().replace(/^https?:\/\/github\.com\//, "");
    const parts = clean.split("/").filter(Boolean);
    if (parts.length !== 2) return null;
    return { owner: parts[0], repo: parts[1] };
  }

  async function loadBranches() {
    const parsed = parseRepo(repoInput);
    if (!parsed) {
      setRepoError("Enter a valid repo: owner/repo or github.com/owner/repo");
      return;
    }
    setRepoError(null);
    setLoadingBranches(true);
    setBranchesLoaded(false);
    try {
      const res = await fetch(
        `/api/github/branches?owner=${encodeURIComponent(parsed.owner)}&repo=${encodeURIComponent(parsed.repo)}`
      );
      if (!res.ok) {
        const d = (await res.json()) as { message?: string };
        setRepoError(d.message ?? `Could not access ${parsed.owner}/${parsed.repo}. Check the repo name and token permissions.`);
        return;
      }
      const data = (await res.json()) as { branches: Branch[] };
      setBranches(data.branches);
      setBranchesLoaded(true);
      // pick default branch if present
      const main = data.branches.find((b) => b.name === "main") ?? data.branches.find((b) => b.name === "master") ?? data.branches[0];
      if (main) setBaseBranch(main.name);
    } catch {
      setRepoError("Network error — check your connection and try again.");
    } finally {
      setLoadingBranches(false);
    }
  }

  async function handleSubmit() {
    const parsed = parseRepo(repoInput);
    if (!parsed) { setRepoError("Invalid repo"); return; }
    if (!branchName.trim()) return;

    setSubmitting(true);
    setSubmitError(null);
    setResult(null);

    try {
      const res = await fetch("/api/github/pr", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          owner: parsed.owner,
          repo: parsed.repo,
          baseBranch,
          branchName: branchName.trim(),
          title: prTitle.trim() || `feat: generated ${config.name}`,
          body: prBody,
          config,
          endpoints,
          entities,
          gitConfig,
        }),
      });

      const data = (await res.json()) as PRResult & { error?: string; message?: string };
      if (!res.ok) {
        setSubmitError(data.message ?? data.error ?? "Something went wrong");
        return;
      }
      setResult(data);
      toast({ title: "PR opened!", description: `#${data.prNumber} — ${data.fileCount} files pushed`, kind: "success" });
    } catch {
      setSubmitError("Network error — check your connection.");
    } finally {
      setSubmitting(false);
    }
  }

  if (loadingStatus) {
    return (
      <div className="flex items-center gap-2 text-xs text-muted-foreground py-6">
        <Loader2 className="h-3.5 w-3.5 animate-spin" /> Checking GitHub connection…
      </div>
    );
  }

  if (!ghStatus?.connected) {
    return (
      <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-6 text-center space-y-4">
        <div className="mx-auto h-10 w-10 rounded-xl bg-white/[0.04] border border-white/[0.06] grid place-items-center">
          <Github className="h-5 w-5 text-muted-foreground" />
        </div>
        <div>
          <p className="text-sm font-medium">GitHub not connected</p>
          <p className="text-xs text-muted-foreground mt-1">
            Connect your GitHub account to push generated code and open PRs directly from Helios.
          </p>
        </div>
        <a
          href="/api/auth/github?mode=connect&returnTo=/git-settings"
          className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/[0.04] px-4 py-2 text-xs font-medium hover:bg-white/[0.07] transition-colors"
        >
          <Github className="h-3.5 w-3.5" /> Connect GitHub
        </a>
      </div>
    );
  }

  if (result) {
    return (
      <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/[0.06] p-6 space-y-4">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-2.5">
            <div className="h-8 w-8 rounded-full bg-emerald-500/20 grid place-items-center">
              <Check className="h-4 w-4 text-emerald-300" />
            </div>
            <div>
              <p className="text-sm font-semibold text-emerald-200">PR opened successfully</p>
              <p className="text-[11px] text-emerald-300/70">
                {result.fileCount} files committed to <code className="font-mono">{result.branchName}</code>
              </p>
            </div>
          </div>
          <button onClick={() => setResult(null)} className="text-muted-foreground hover:text-foreground">
            <X className="h-4 w-4" />
          </button>
        </div>
        <a
          href={result.prUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-between rounded-lg border border-emerald-500/30 bg-emerald-500/[0.08] px-3 py-2.5 text-xs hover:bg-emerald-500/[0.12] transition-colors"
        >
          <span className="font-mono text-emerald-200">PR #{result.prNumber}</span>
          <ExternalLink className="h-3.5 w-3.5 text-emerald-300" />
        </a>
        <Button
          variant="ghost"
          size="sm"
          className="w-full text-xs"
          onClick={() => setResult(null)}
        >
          Open another PR
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Connected account */}
      <div className="flex items-center justify-between rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2.5">
        <div className="flex items-center gap-2 text-xs">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
          <span className="text-emerald-300 font-medium">@{ghStatus.login}</span>
          <span className="text-muted-foreground">connected</span>
        </div>
        <a
          href="/settings"
          className="text-[10px] text-muted-foreground hover:text-foreground transition-colors"
        >
          Manage
        </a>
      </div>

      {/* Repo input */}
      <div className="space-y-1.5">
        <label className="text-xs font-medium text-muted-foreground">Target repository</label>
        <div className="flex gap-2">
          <input
            value={repoInput}
            onChange={(e) => { setRepoInput(e.target.value); setRepoError(null); setBranchesLoaded(false); }}
            onKeyDown={(e) => e.key === "Enter" && loadBranches()}
            placeholder="owner/repo or github.com/owner/repo"
            className="flex-1 rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-xs font-mono placeholder:text-muted-foreground/50 focus:outline-none focus:ring-1 focus:ring-brand-500/40"
          />
          <Button
            variant="secondary"
            size="sm"
            onClick={loadBranches}
            disabled={loadingBranches || !repoInput.trim()}
          >
            {loadingBranches ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
            {branchesLoaded ? "Reload" : "Load"}
          </Button>
        </div>
        {repoError && (
          <p className="flex items-center gap-1.5 text-[11px] text-red-400">
            <AlertCircle className="h-3 w-3" /> {repoError}
          </p>
        )}
      </div>

      {branchesLoaded && (
        <>
          {/* Base branch selector */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-muted-foreground">Base branch (merge target)</label>
              <div className="relative">
                <select
                  value={baseBranch}
                  onChange={(e) => setBaseBranch(e.target.value)}
                  className="w-full appearance-none rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-2 pr-7 text-xs focus:outline-none focus:ring-1 focus:ring-brand-500/40"
                >
                  {branches.map((b) => (
                    <option key={b.name} value={b.name} className="bg-[#0a0a0f]">
                      {b.name}{b.protected ? " 🔒" : ""}
                    </option>
                  ))}
                </select>
                <ChevronDown className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
              </div>
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-muted-foreground">Feature branch (new)</label>
              <div className="relative">
                <GitBranch className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
                <input
                  value={branchName}
                  onChange={(e) => setBranchName(e.target.value)}
                  className="w-full rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-2 pl-8 text-xs font-mono focus:outline-none focus:ring-1 focus:ring-brand-500/40"
                />
              </div>
            </div>
          </div>

          {/* PR title */}
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">PR title</label>
            <input
              value={prTitle}
              onChange={(e) => setPrTitle(e.target.value)}
              className="w-full rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-xs focus:outline-none focus:ring-1 focus:ring-brand-500/40"
            />
          </div>

          {/* PR body */}
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">PR description</label>
            <textarea
              value={prBody}
              onChange={(e) => setPrBody(e.target.value)}
              rows={8}
              className="w-full resize-y rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-xs font-mono leading-relaxed focus:outline-none focus:ring-1 focus:ring-brand-500/40"
            />
          </div>

          {/* File count hint */}
          <p className="text-[11px] text-muted-foreground">
            This will commit all generated files for <span className="text-foreground font-medium">{config.name}</span> ({config.language}/{config.framework}) to <code className="font-mono text-brand-300">{branchName}</code> and open a PR against <code className="font-mono">{baseBranch}</code>.
          </p>

          {submitError && (
            <div className="flex items-start gap-2 rounded-lg border border-red-500/20 bg-red-500/[0.06] px-3 py-2.5 text-xs text-red-300">
              <AlertCircle className="h-3.5 w-3.5 mt-0.5 shrink-0" />
              <span>{submitError}</span>
            </div>
          )}

          <Button
            variant="glow"
            size="sm"
            className={cn("w-full", submitting && "opacity-70 pointer-events-none")}
            onClick={handleSubmit}
            disabled={submitting || !branchName.trim()}
          >
            {submitting ? (
              <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Pushing files…</>
            ) : (
              <><Github className="h-3.5 w-3.5" /> Push files &amp; Open PR</>
            )}
          </Button>
        </>
      )}
    </div>
  );
}
