import { cookies } from "next/headers";
import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { generate } from "@/lib/generators";
import { stackConfigSchema, endpointSchema, entitySchema } from "@/lib/schema";

export const runtime = "nodejs";

const bodySchema = z.object({
  config: stackConfigSchema,
  endpoints: z.array(endpointSchema),
  entities: z.array(entitySchema),
  repoName: z.string().min(1).max(100).regex(/^[a-zA-Z0-9_.-]+$/),
  private: z.boolean().optional().default(false),
});

async function ghFetch(
  path: string,
  token: string,
  options: RequestInit = {}
): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "Helios-App/1.0",
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
}

export async function POST(req: NextRequest) {
  const cookieStore = await cookies();
  const token = cookieStore.get("github_token")?.value;
  if (!token) {
    return NextResponse.json({ error: "not_authenticated" }, { status: 401 });
  }

  const body = await req.json();
  const parsed = bodySchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "invalid_request", issues: parsed.error.issues }, { status: 400 });
  }

  const { config, endpoints, entities, repoName, private: isPrivate } = parsed.data;

  // Generate all files
  const files = generate(config as Parameters<typeof generate>[0], endpoints, entities);

  // 1. Create the repository (fall back to existing if name is taken)
  type RepoShape = {
    full_name: string;
    html_url: string;
    default_branch: string;
    owner: { login: string };
    name: string;
  };

  const createRes = await ghFetch("/user/repos", token, {
    method: "POST",
    body: JSON.stringify({
      name: repoName,
      description: `Generated by Helios — ${config.language}/${config.framework}`,
      auto_init: true,
      private: isPrivate,
    }),
  });

  let repo: RepoShape;

  if (createRes.ok) {
    repo = (await createRes.json()) as RepoShape;
  } else if (createRes.status === 422) {
    // Repo may already exist — fetch the authenticated user's login then GET the repo
    const userRes = await ghFetch("/user", token);
    if (!userRes.ok) {
      return NextResponse.json({ error: "repo_create_failed" }, { status: 422 });
    }
    const ghUser = (await userRes.json()) as { login: string };
    const getRes = await ghFetch(`/repos/${ghUser.login}/${repoName}`, token);
    if (!getRes.ok) {
      const err = await createRes.json();
      return NextResponse.json({ error: "repo_create_failed", detail: err }, { status: 422 });
    }
    repo = (await getRes.json()) as RepoShape;
  } else {
    const err = await createRes.json();
    return NextResponse.json({ error: "repo_create_failed", detail: err }, { status: 422 });
  }

  const owner = repo.owner.login;
  const name = repo.name;
  const branch = repo.default_branch;

  // 2. Get the base commit SHA
  const refRes = await ghFetch(`/repos/${owner}/${name}/git/refs/heads/${branch}`, token);
  const refData = (await refRes.json()) as { object: { sha: string } };
  const baseCommitSha = refData.object.sha;

  // 3. Get the base tree SHA
  const commitRes = await ghFetch(`/repos/${owner}/${name}/git/commits/${baseCommitSha}`, token);
  const commitData = (await commitRes.json()) as { tree: { sha: string } };
  const baseTreeSha = commitData.tree.sha;

  // 4. Create blobs for all files (in parallel, capped at 10 concurrent)
  const blobEntries: { path: string; mode: string; type: string; sha: string }[] = [];
  const chunkSize = 10;
  for (let i = 0; i < files.length; i += chunkSize) {
    const chunk = files.slice(i, i + chunkSize);
    const blobs = await Promise.all(
      chunk.map(async (f) => {
        const blobRes = await ghFetch(`/repos/${owner}/${name}/git/blobs`, token, {
          method: "POST",
          body: JSON.stringify({
            content: Buffer.from(f.content, "utf8").toString("base64"),
            encoding: "base64",
          }),
        });
        const blob = (await blobRes.json()) as { sha: string };
        return {
          path: f.path,
          mode: "100644" as const,
          type: "blob" as const,
          sha: blob.sha,
        };
      })
    );
    blobEntries.push(...blobs);
  }

  // 5. Create a tree
  const treeRes = await ghFetch(`/repos/${owner}/${name}/git/trees`, token, {
    method: "POST",
    body: JSON.stringify({ base_tree: baseTreeSha, tree: blobEntries }),
  });
  const treeData = (await treeRes.json()) as { sha: string };

  // 6. Create a commit
  const newCommitRes = await ghFetch(`/repos/${owner}/${name}/git/commits`, token, {
    method: "POST",
    body: JSON.stringify({
      message: `chore: initial backend generated by Helios\n\nStack: ${config.language} / ${config.framework} / ${config.database}`,
      tree: treeData.sha,
      parents: [baseCommitSha],
    }),
  });
  const newCommit = (await newCommitRes.json()) as { sha: string };

  // 7. Update the branch ref
  await ghFetch(`/repos/${owner}/${name}/git/refs/heads/${branch}`, token, {
    method: "PATCH",
    body: JSON.stringify({ sha: newCommit.sha }),
  });

  return NextResponse.json({
    url: repo.html_url,
    fullName: repo.full_name,
    fileCount: files.length,
  });
}
