import { cookies } from "next/headers";
import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { generate } from "@/lib/generators";
import { stackConfigSchema, endpointSchema, entitySchema } from "@/lib/schema";

export const runtime = "nodejs";

const bodySchema = z.object({
  config: stackConfigSchema,
  endpoints: z.array(endpointSchema),
  entities: z.array(entitySchema),
  repoName: z.string().min(1).max(100).regex(/^[a-zA-Z0-9_.-]+$/),
  private: z.boolean().optional().default(false),
});

async function ghFetch(
  path: string,
  token: string,
  options: RequestInit = {}
): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "Helios-App/1.0",
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
}

export async function POST(req: NextRequest) {
  const cookieStore = await cookies();
  const token = cookieStore.get("github_token")?.value;
  if (!token) {
    return NextResponse.json({ error: "not_authenticated" }, { status: 401 });
  }

  const body = await req.json();
  const parsed = bodySchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "invalid_request", issues: parsed.error.issues }, { status: 400 });
  }

  const { config, endpoints, entities, repoName, private: isPrivate } = parsed.data;

  // Generate all files
  const files = generate(config as Parameters<typeof generate>[0], endpoints, entities);

  // 1. Create the repository (fall back to existing if name is taken)
  type RepoShape = {
    full_name: string;
    html_url: string;
    default_branch: string;
    owner: { login: string };
    name: string;
  };

  const createRes = await ghFetch("/user/repos", token, {
    method: "POST",
    body: JSON.stringify({
      name: repoName,
      description: `Generated by Helios — ${config.language}/${config.framework}`,
      auto_init: true,
      private: isPrivate,
    }),
  });

  let repo: RepoShape;

  if (createRes.ok) {
    repo = (await createRes.json()) as RepoShape;
  } else if (createRes.status === 422) {
    // Repo may already exist — fetch the authenticated user's login then GET the repo
    const userRes = await ghFetch("/user", token);
    if (!userRes.ok) {
      return NextResponse.json({ error: "repo_create_failed" }, { status: 422 });
    }
    const ghUser = (await userRes.json()) as { login: string };
    const getRes = await ghFetch(`/repos/${ghUser.login}/${repoName}`, token);
    if (!getRes.ok) {
      const err = await createRes.json();
      return NextResponse.json({ error: "repo_create_failed", detail: err }, { status: 422 });
    }
    repo = (await getRes.json()) as RepoShape;
  } else {
    const err = await createRes.json();
    return NextResponse.json({ error: "repo_create_failed", detail: err }, { status: 422 });
  }

  const owner = repo.owner.login;
  const name = repo.name;
  const branch = repo.default_branch;

  console.log(`[github/push] pushing ${files.length} files to ${owner}/${name} on branch ${branch}`);

  // 2. Get the current HEAD OID (needed by createCommitOnBranch)
  const refRes = await ghFetch(`/repos/${owner}/${name}/git/refs/heads/${branch}`, token);
  if (!refRes.ok) {
    const err = await refRes.json();
    console.error("[github/push] get ref failed:", err);
    return NextResponse.json({ error: "get_ref_failed", detail: err }, { status: 502 });
  }
  const refData = (await refRes.json()) as { object?: { sha: string } };
  const headOid = refData.object?.sha;
  if (!headOid) {
    return NextResponse.json({ error: "missing_head_oid", detail: refData }, { status: 502 });
  }
  console.log("[github/push] HEAD OID:", headOid);

  // 3. Push all files atomically via GraphQL createCommitOnBranch
  const additions = files.map((f) => ({
    path: f.path,
    contents: Buffer.from(f.content, "utf8").toString("base64"),
  }));

  const gqlRes = await fetch("https://api.github.com/graphql", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "User-Agent": "Helios-App/1.0",
    },
    body: JSON.stringify({
      query: `mutation CreateCommit($input: CreateCommitOnBranchInput!) {
        createCommitOnBranch(input: $input) {
          commit { oid url }
        }
      }`,
      variables: {
        input: {
          branch: { repositoryNameWithOwner: `${owner}/${name}`, branchName: branch },
          message: {
            headline: "chore: initial backend generated by Helios",
            body: `Stack: ${config.language} / ${config.framework} / ${config.database}`,
          },
          fileChanges: { additions },
          expectedHeadOid: headOid,
        },
      },
    }),
  });

  const gqlJson = (await gqlRes.json()) as {
    data?: { createCommitOnBranch: { commit: { oid: string; url: string } } };
    errors?: { message: string }[];
  };

  if (gqlJson.errors?.length) {
    console.error("[github/push] GraphQL commit failed:", JSON.stringify(gqlJson.errors));
    return NextResponse.json({ error: "commit_failed", detail: gqlJson.errors }, { status: 502 });
  }

  const commitOid = gqlJson.data?.createCommitOnBranch?.commit?.oid;
  console.log(`[github/push] done — commit ${commitOid}`);

  return NextResponse.json({
    url: repo.html_url,
    fullName: repo.full_name,
    fileCount: files.length,
  });
}
