import { ImageResponse } from "next/og";
import { get } from "@/lib/share-store";

export const runtime = "nodejs";

export const alt = "Architected by Helios";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function Image({ params }: { params: { slug: string } }) {
  const shared = get(params.slug);

  const name = shared?.proposal.config.name ?? "Architecture";
  const summary =
    shared?.proposal.summary ??
    "An AI-designed backend architecture, generated by Helios.";
  const stack = shared
    ? [
        shared.proposal.config.language,
        shared.proposal.config.framework,
        shared.proposal.config.database,
        shared.proposal.config.cache,
        shared.proposal.config.queue,
        shared.proposal.config.deployment,
      ].filter(Boolean)
    : [];
  const cost = shared
    ? `$${Math.round(shared.proposal.predictions.monthlyCostUsd).toLocaleString()}/mo`
    : null;
  const p99 = shared
    ? `~${Math.round(shared.proposal.predictions.p99LatencyMs)}ms p99`
    : null;
  const compliance = shared?.proposal.predictions.compliance ?? [];

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          background:
            "linear-gradient(135deg, #08101e 0%, #0b0f1a 60%, #1a0b2e 100%)",
          color: "#e6edf3",
          padding: 64,
          fontFamily: "Inter, sans-serif",
          position: "relative",
        }}
      >
        {/* aurora glow */}
        <div
          style={{
            position: "absolute",
            top: -200,
            left: 200,
            width: 900,
            height: 500,
            background:
              "radial-gradient(closest-side, rgba(46,143,255,0.45), transparent 70%)",
            filter: "blur(40px)",
          }}
        />
        <div
          style={{
            position: "absolute",
            bottom: -160,
            right: -80,
            width: 700,
            height: 500,
            background:
              "radial-gradient(closest-side, rgba(168,85,247,0.4), transparent 70%)",
            filter: "blur(40px)",
          }}
        />

        {/* header */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 16,
          }}
        >
          <div
            style={{
              width: 48,
              height: 48,
              borderRadius: 12,
              background:
                "linear-gradient(135deg, #56b2ff 0%, #2e8fff 50%, #a855f7 100%)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "white",
              fontWeight: 800,
              fontSize: 24,
            }}
          >
            H
          </div>
          <div style={{ display: "flex", flexDirection: "column" }}>
            <div style={{ fontSize: 22, fontWeight: 700 }}>Helios</div>
            <div style={{ fontSize: 14, color: "#8d9bb1", marginTop: -2 }}>
              AI Platform Engineer
            </div>
          </div>
          <div style={{ flex: 1 }} />
          <div
            style={{
              fontSize: 14,
              color: "#a1a8b6",
              padding: "6px 14px",
              border: "1px solid rgba(255,255,255,0.1)",
              borderRadius: 999,
              display: "flex",
              alignItems: "center",
              gap: 8,
            }}
          >
            <span
              style={{
                width: 8,
                height: 8,
                borderRadius: 999,
                background: "#34d399",
              }}
            />
            Architected by Helios
          </div>
        </div>

        {/* title */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            marginTop: 64,
          }}
        >
          <div
            style={{
              fontSize: 28,
              color: "#8d9bb1",
              fontWeight: 500,
              letterSpacing: -0.5,
            }}
          >
            Architecture · {name}
          </div>
          <div
            style={{
              fontSize: 64,
              fontWeight: 700,
              lineHeight: 1.05,
              letterSpacing: -1.5,
              marginTop: 12,
              maxWidth: 1000,
              backgroundImage: "linear-gradient(180deg, #fff, #9aa4b6)",
              backgroundClip: "text",
              color: "transparent",
            }}
          >
            {truncate(summary, 140)}
          </div>
        </div>

        <div style={{ flex: 1 }} />

        {/* stack chips + metrics */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 22,
          }}
        >
          {stack.length ? (
            <div style={{ display: "flex", flexWrap: "wrap", gap: 10 }}>
              {stack.map((s) => (
                <div
                  key={s}
                  style={{
                    fontSize: 22,
                    padding: "8px 16px",
                    borderRadius: 10,
                    border: "1px solid rgba(255,255,255,0.12)",
                    background: "rgba(255,255,255,0.04)",
                    color: "#e6edf3",
                    fontFamily: "ui-monospace, SFMono-Regular, monospace",
                  }}
                >
                  {s}
                </div>
              ))}
            </div>
          ) : null}

          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 28,
              fontSize: 22,
              color: "#cbd2dc",
            }}
          >
            {cost ? <Metric label="Cost" value={cost} /> : null}
            {p99 ? <Metric label="Latency" value={p99} /> : null}
            {compliance.length ? (
              <Metric label="Posture" value={compliance.join(" · ")} />
            ) : null}
          </div>
        </div>
      </div>
    ),
    { ...size }
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
      <span style={{ color: "#8d9bb1", fontSize: 16 }}>{label}</span>
      <span style={{ color: "#e6edf3", fontWeight: 600 }}>{value}</span>
    </div>
  );
}

function truncate(s: string, n: number) {
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + "…";
}
