import { cookies } from "next/headers";
import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { generate } from "@/lib/generators";
import { stackConfigSchema, endpointSchema, entitySchema } from "@/lib/schema";
import type { GitConfig } from "@/lib/git-config";

export const runtime = "nodejs";

async function ghFetch(path: string, token: string, init?: RequestInit) {
  return fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "Helios-App/1.0",
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
}

const bodySchema = z.object({
  owner: z.string().min(1).max(100),
  repo: z.string().min(1).max(100),
  baseBranch: z.string().min(1).max(255),
  branchName: z.string().min(1).max(255),
  title: z.string().min(1).max(200),
  body: z.string().max(10000).optional(),
  config: stackConfigSchema,
  endpoints: z.array(endpointSchema).max(200),
  entities: z.array(entitySchema).max(50).optional(),
  gitConfig: z.record(z.unknown()).optional(),
});

// POST /api/github/pr
// Full flow: create branch → commit generated files → open PR → return PR URL
export async function POST(req: NextRequest) {
  const cookieStore = await cookies();
  const token = cookieStore.get("github_token")?.value;
  if (!token) {
    return NextResponse.json(
      { error: "no_token", message: "GitHub not connected. Connect from Settings → Integrations." },
      { status: 401 }
    );
  }

  let raw: unknown;
  try { raw = await req.json(); } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }
  const parsed = bodySchema.safeParse(raw);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "invalid_request", issues: parsed.error.flatten() },
      { status: 400 }
    );
  }

  const {
    owner, repo, baseBranch, branchName, title,
    body: prBody, config, endpoints, entities, gitConfig,
  } = parsed.data;

  // 1. Generate files
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const files = generate(config, endpoints, entities ?? [], gitConfig as any as GitConfig | undefined);

  // 2. Get base branch SHA
  const refRes = await ghFetch(`/repos/${owner}/${repo}/git/refs/heads/${baseBranch}`, token);
  if (!refRes.ok) {
    return NextResponse.json(
      { error: "base_branch_not_found", message: `Branch '${baseBranch}' not found in ${owner}/${repo}` },
      { status: 404 }
    );
  }
  const refData = (await refRes.json()) as { object?: { sha: string } };
  const baseSha = refData.object?.sha;
  if (!baseSha) return NextResponse.json({ error: "ref_missing_sha" }, { status: 502 });

  // 3. Create feature branch (ignore 422 = already exists)
  const branchRes = await ghFetch(`/repos/${owner}/${repo}/git/refs`, token, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  });
  if (!branchRes.ok && branchRes.status !== 422) {
    const bd = (await branchRes.json()) as { message?: string };
    return NextResponse.json(
      { error: "branch_create_failed", message: bd.message },
      { status: 502 }
    );
  }

  // 4. Commit files via GitHub GraphQL (handles base64 + large changesets)
  const additions = files.map((f) => ({
    path: f.path,
    contents: Buffer.from(f.content, "utf8").toString("base64"),
  }));

  const gqlRes = await fetch("https://api.github.com/graphql", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "User-Agent": "Helios-App/1.0",
    },
    body: JSON.stringify({
      query: `mutation CreateCommit($input: CreateCommitOnBranchInput!) {
        createCommitOnBranch(input: $input) {
          commit { oid url }
        }
      }`,
      variables: {
        input: {
          branch: { repositoryNameWithOwner: `${owner}/${repo}`, branchName },
          message: {
            headline: `feat: generated ${config.language}/${config.framework} backend by Helios`,
            body: `Stack: ${config.language} / ${config.framework} / ${config.database}\nGenerated by Helios — https://helios.sh`,
          },
          fileChanges: { additions },
          expectedHeadOid: baseSha,
        },
      },
    }),
  });

  if (!gqlRes.ok) {
    return NextResponse.json({ error: "commit_failed", message: "GraphQL request failed" }, { status: 502 });
  }
  const gqlJson = (await gqlRes.json()) as {
    data?: { createCommitOnBranch: { commit: { oid: string; url: string } } };
    errors?: { message: string; type?: string }[];
  };
  if (gqlJson.errors?.length) {
    return NextResponse.json(
      { error: "commit_failed", message: gqlJson.errors[0].message },
      { status: 422 }
    );
  }

  // 5. Open PR
  const prRes = await ghFetch(`/repos/${owner}/${repo}/pulls`, token, {
    method: "POST",
    body: JSON.stringify({
      title,
      body: prBody ?? "",
      head: branchName,
      base: baseBranch,
      draft: false,
    }),
  });

  if (!prRes.ok) {
    const pd = (await prRes.json()) as { message?: string; errors?: { message: string }[] };
    const msg = pd.message ?? pd.errors?.[0]?.message ?? "PR creation failed";
    return NextResponse.json(
      { error: "pr_create_failed", message: msg },
      { status: prRes.status < 500 ? prRes.status : 502 }
    );
  }

  const prData = (await prRes.json()) as { html_url: string; number: number };
  return NextResponse.json({
    prUrl: prData.html_url,
    prNumber: prData.number,
    branchName,
    fileCount: files.length,
  });
}
